gwas: '/gpfs/data/im-lab/nas40t2/Data/SummaryResults/imputed_gwas_hg38_1.1/imputed_pgc.scz2.txt.gz'  
# gwas: '/gpfs/data/im-lab/nas40t2/yanyul/GitHub/brainxcan/test.txt.gz'
datadir: '/gpfs/data/im-lab/nas40t2/yanyul/data/brainxcan_data'
# outdir: 'output'
# prefix: 'test'
# brainxcan_path: '/gpfs/data/im-lab/nas40t2/yanyul/GitHub/brainxcan'

gwas_pop: 'EUR'
snpid: 'variant_id'
effect_allele: 'effect_allele'
non_effect_allele: 'non_effect_allele'
zscore: 'zscore'
sample_size: 'sample_size'
allele_frequency: 'frequency'
chr: 'chromosome'

# model_type: 'ridge'
# idp_type: 'residual'
signif_pval: 1e-8
signif_max_idps: 5
# ld_clump_yaml: '{datadir}/mr/ld_clump.yaml'
     
rscript_exe: 'Rscript' 
# python_exe: 'python'
