name: brainxcan
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - fastparquet=0.4
  - numpy=1.18
  - pandas=1.1
  - pandas-plink=2.2.2
  - python=3.7.8
  - scipy=1.5
  - snakemake=6.1
  # - seaborn=0.11.0
  # - ipython=7.19.0
  # - jupyter=1.0.0
  # - matplotlib=3.3.2

